### ISSUE TITLE
added support for non-made-up facts

### ISSUE THREAD

**Issue by VitamintK** [jwad96/fun-fact-generator#1]
> fact: a thing that is known or proved to be true.

> made-up: 1. wearing makeup.
> "her immaculately made-up face"
> 2. invented; not true.
> "a made-up story"

You see, a "made up fact" is therefore a not true thing that is know to be true: according to the known laws of physics (which are known to be true), this is an oxymoron.  I request the support for non-made-up facts.  

P.s. A made-up fact is also know as a factoid!
> factoid
> 1: an invented fact believed to be true because it appears in print

**Comment by jwad96** [comment]
Thank you for your vigilance. However -- and understandably so, as this project is extremely complex  -- there seems to be some confusion on your end. 

You are mistaking a "made up" fact with one that is false. It is entirely possible that a statement can be both conjured up and known to be true at the same time, thus making it a fact. 

That being said, after this project has progressed and we are producing facts every day, we at fun-fact-generator are comforted knowing we can count on you to keep us honest if ever the situation arises that we release a made up fact that is false (however unlikely that may be).
##
Since support for your desired feature is inherent in the project as it stands, this issue is closed.
