### ISSUE TITLE
where are the fax

### ISSUE THREAD

**Issue by VitamintK** [jwad96/fun-fact-generator#2]
we were promised "fun facts every day".  Yet what we have received is closer to "no fun facts any day".  Please rectify.

Best regards,
your friend,
Kevin

**Comment by jwad96** [comment]
Thanks for reaching out! We understand your concern. At the time of that claim we, too, believed that (fake) fun facts would be delivered daily in a timely manner.  However, the fact is that sometimes things don't pan out the way we originally plan. Unforeseen obstacles and other urgent matters have delayed the production of this project considerably. 

In light of this, I hope you can appreciate that we here are just as frustrated as you are and are working tirelessly to get to a place where we can move production along. Sit tight! We'll be done before we know it. Until then, we thank you and all our other supporters for your patience. 

This issue is closed. 

Best,
Jwad

**Comment by VitamintK** [comment]
this is fukin bullshit i hopeu rot in hell #wherearethefacts
